extends RefCounted
class_name Enums

enum Class{ 
	None,
	Mage = 1,
	Cleric,
	Warrior,
	Assassin,
	Thief,
	Bard,
	Druid,
	Bandit,
	Paladin,
	Hunter,
	Worker,
	Pirat
}

enum Race{ 
	None,
	Human = 1,
	Elf,
	Drow,
	Gnome,
	Dwarf
}

enum Home{
	None = 0,
	Ullathorpe = 1,
	Nix,
	Banderbill,
	Lindos,
	Arghal,
	Arkhein,
	LastCity
};

enum TileState {
	None = 0,
	Blocked = 1 << 0, 
	Roof = 1 << 1,
	Water = 1 << 2,
} 

enum Heading{
	None,
	North,
	East,
	South,
	West,
}

enum Skill{
	None = 0,
	Magia = 1,
	Robar = 2,
	Tacticas = 3,
	Armas = 4,
	Meditar = 5,
	Apunalar = 6,
	Ocultarse = 7,
	Supervivencia = 8,
	Talar = 9,
	Comerciar = 10,
	Defensa = 11,
	Pesca = 12,
	Mineria = 13,
	Carpinteria = 14,
	Herreria = 15,
	Liderazgo = 16,
	Domar = 17,
	Proyectiles = 18,
	Wrestling = 19,
	Navegacion = 20,

	# FIXME: Revisar esto!
	FundirMetal = 88
}

enum eOBJType {
	eOBJType_Null = 0,
	eOBJType_otUseOnce = 1,
	eOBJType_otWeapon = 2,
	eOBJType_otArmadura = 3,
	eOBJType_otArboles = 4,
	eOBJType_otGuita = 5,
	eOBJType_otPuertas = 6,
	eOBJType_otContenedores = 7,
	eOBJType_otCarteles = 8,
	eOBJType_otLlaves = 9,
	eOBJType_otForos = 10,
	eOBJType_otPociones = 11,
	eOBJType_otBebidas = 13,
	eOBJType_otLena = 14,
	eOBJType_otFogata = 15,
	eOBJType_otESCUDO = 16,
	eOBJType_otCASCO = 17,
	eOBJType_otAnillo = 18,
	eOBJType_otTeleport = 19,
	eOBJType_otYacimiento = 22,
	eOBJType_otMinerales = 23,
	eOBJType_otPergaminos = 24,
	eOBJType_otInstrumentos = 26,
	eOBJType_otYunque = 27,
	eOBJType_otFragua = 28,
	eOBJType_otBarcos = 31,
	eOBJType_otFlechas = 32,
	eOBJType_otBotellaVacia = 33,
	eOBJType_otBotellaLlena = 34,
	
	#No se usa 
	eOBJType_otManchas = 35,
	eOBJType_otArbolElfico = 36,
	eOBJType_otMochilas = 37,
	eOBJType_otYacimientoPez = 38,
	eOBJType_otCualquiera = 1000
}

enum Messages {
	DontSeeAnything,
	NPCSwing,
	NPCKillUser,
	BlockedWithShieldUser,
	BlockedWithShieldother,
	UserSwing,
	SafeModeOn,
	SafeModeOff,
	ResuscitationSafeOff,
	ResuscitationSafeOn,
	NobilityLost,
	CantUseWhileMeditating,
	NPCHitUser,
	UserHitNPC,
	UserAttackedSwing,
	UserHittedByUser,
	UserHittedUser,
	WorkRequestTarget,
	HaveKilledUser,
	UserKill,
	EarnExp,
	Home,
	CancelHome,
	FinishHome
};
	
enum FontTypeNames {
	FontType_Talk,
	FontType_Fight,
	FontType_Warning,
	FontType_Info,
	FontType_InfoBold,
	FontType_Ejecucion,
	FontType_Party,
	FontType_Veneno,
	FontType_Guild,
	FontType_Server,
	FontType_GuildMsg,
	FontType_Consejo,
	FontType_ConsejoCaos,
	FontType_ConsejoVesA,
	FontType_ConsejoCaosVesA,
	FontType_Centinela,
	FontType_GMMsg,
	FontType_GM,
	FontType_Citizen,
	FontType_Conse,
	FontType_Dios
}

enum PlayerType {
	None = 0,
	User = 1 << 0,         # 1
	Consejero = 1 << 1,    # 2
	SemiDios = 1 << 2,     # 4
	Dios = 1 << 3,         # 8
	Admin = 1 << 4,        # 16
	RoleMaster = 1 << 5,   # 32
	ChaosCouncil = 1 << 6, # 64
	RoyalCouncil = 1 << 7  # 128
}

enum NickColor {
	None = 0,
	IeCriminal = 1 << 0,  # 1
	IeCiudadano = 1 << 1, # 2
	IeAtacable = 1 << 2   # 4
}

enum ServerPacketID {
	Logged,
	RemoveDialogs,
	RemoveCharDialog,
	NavigateToggle,
	Disconnect,
	CommerceEnd,
	BankEnd,
	CommerceInit,
	BankInit,
	UserCommerceInit,
	UserCommerceEnd,
	UserOfferConfirm,
	CommerceChat,
	ShowBlacksmithForm,
	ShowCarpenterForm,
	UpdateSta,
	UpdateMana,
	UpdateHP,
	UpdateGold,
	UpdateBankGold,
	UpdateExp,
	ChangeMap,
	PosUpdate,
	ChatOverHead,
	ConsoleMsg,
	GuildChat,
	ShowMessageBox,
	UserIndexInServer,
	UserCharIndexInServer,
	CharacterCreate,
	CharacterRemove,
	CharacterChangeNick,
	CharacterMove,
	ForceCharMove,
	CharacterChange,
	ObjectCreate,
	ObjectDelete,
	BlockPosition,
	PlayMIDI,
	PlayWave,
	GuildList,
	AreaChanged,
	PauseToggle,
	RainToggle,
	CreateFX,
	UpdateUserStats,
	WorkRequestTarget,
	ChangeInventorySlot,
	ChangeBankSlot,
	ChangeSpellSlot,
	Atributes,
	BlacksmithWeapons,
	BlacksmithArmors,
	CarpenterObjects,
	RestOK,
	ErrorMsg,
	Blind,
	Dumb,
	ShowSignal,
	ChangeNPCInventorySlot,
	UpdateHungerAndThirst,
	Fame,
	MiniStats,
	LevelUp,
	AddForumMsg,
	ShowForumForm,
	SetInvisible,
	DiceRoll,
	MeditateToggle,
	BlindNoMore,
	DumbNoMore,
	SendSkills,
	TrainerCreatureList,
	GuildNews,
	OfferDetails,
	AlianceProposalsList,
	PeaceProposalsList,
	CharacterInfo,
	GuildLeaderInfo,
	GuildMemberInfo,
	GuildDetails,
	ShowGuildFundationForm,
	ParalizeOK,
	ShowUserRequest,
	TradeOK,
	BankOK,
	ChangeUserTradeSlot,
	SendNight,
	Pong,
	UpdateTagAndStatus,
	
	#GM messages
	SpawnList,
	ShowSOSForm,
	ShowMOTDEditionForm,
	ShowGMPanelForm,
	UserNameList,
	ShowDenounces,
	RecordList,
	RecordDetails,

	ShowGuildAlign,
	ShowPartyForm,
	UpdateStrenghtAndDexterity,
	UpdateStrenght,
	UpdateDexterity,
	AddSlots,
	MultiMessage,
	StopWorking,
	CancelOfferItem
}

enum ClientPacketID {
	LoginExistingChar,
	ThrowDices,
	LoginNewChar,
	Talk,
	Yell,
	Whisper,
	Walk,
	RequestPositionUpdate,
	Attack,
	PickUp,
	SafeToggle,
	ResuscitationSafeToggle,
	RequestGuildLeaderInfo,
	RequestAtributes,
	RequestFame,
	RequestSkills,
	RequestMiniStats,
	CommerceEnd,
	UserCommerceEnd,
	UserCommerceConfirm,
	CommerceChat,
	BankEnd,
	UserCommerceOk,
	UserCommerceReject,
	Drop,
	CastSpell,
	LeftClick,
	DoubleClick,
	Work,
	UseSpellMacro,
	UseItem,
	CraftBlacksmith,
	CraftCarpenter,
	WorkLeftClick,
	CreateNewGuild,
	SpellInfo,
	EquipItem,
	ChangeHeading,
	ModifySkills,
	Train,
	CommerceBuy,
	BankExtractItem,
	CommerceSell,
	BankDeposit,
	ForumPost,
	MoveSpell,
	MoveBank,
	ClanCodexUpdate,
	UserCommerceOffer,
	GuildAcceptPeace,
	GuildRejectAlliance,
	GuildRejectPeace,
	GuildAcceptAlliance,
	GuildOfferPeace,
	GuildOfferAlliance,
	GuildAllianceDetails,
	GuildPeaceDetails,
	GuildRequestJoinerInfo,
	GuildAlliancePropList,
	GuildPeacePropList,
	GuildDeclareWar,
	GuildNewWebsite,
	GuildAcceptNewMember,
	GuildRejectNewMember,
	GuildKickMember,
	GuildUpdateNews,
	GuildMemberInfo,
	GuildOpenElections,
	GuildRequestMembership,
	GuildRequestDetails,
	Online,
	Quit,
	GuildLeave,
	RequestAccountState,
	PetStand,
	PetFollow,
	ReleasePet,
	TrainList,
	Rest,
	Meditate,
	Resucitate,
	Heal,
	Help,
	RequestStats,
	CommerceStart,
	BankStart,
	Enlist,
	Information,
	Reward,
	RequestMOTD,
	Uptime,
	PartyLeave,
	PartyCreate,
	PartyJoin,
	Inquiry,
	GuildMessage,
	PartyMessage,
	CentinelReport,
	GuildOnline,
	PartyOnline,
	CouncilMessage,
	RoleMasterRequest,
	GMRequest,
	BugReport,
	ChangeDescription,
	GuildVote,
	Punishments,
	ChangePassword,
	Gamble,
	InquiryVote,
	LeaveFaction,
	BankExtractGold,
	BankDepositGold,
	Denounce,
	GuildFundate,
	GuildFundation,
	PartyKick,
	PartySetLeader,
	PartyAcceptMember,
	Ping,
	RequestPartyForm,
	ItemUpgrade,
	GMCommands,
	InitCrafting,
	Home,
	ShowGuildNews,
	ShareNpc,
	StopSharingNpc,
	Consultation,
	MoveItem
}
